PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);
CREATE TABLE submissions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    problem INTEGER NOT NULL,
    user INTEGER NOT NULL,
    source TEXT NOT NULL,
    status TEXT DEFAULT 'PENDING', time text,
    FOREIGN KEY (problem) REFERENCES problem(id),
    FOREIGN KEY (user) REFERENCES user(id)
);
CREATE TABLE answers (
  id integer primary key,
  imports text not null,
  body text not null
);
INSERT INTO answers VALUES(1,'','def answer : Prop := False');
INSERT INTO answers VALUES(2,'import Mathlib.Data.Real.Basic','def answer : Set (ℝ → ℝ) := {0}');
INSERT INTO answers VALUES(3,'import Mathlib.Data.Real.Basic','def answer : Set (ℝ × ℝ × ℝ) := {(0, 0, 0), (1, 1, 1)}');
INSERT INTO answers VALUES(4,'import Mathlib.Data.Int.Basic','def answer : ℤ := 15');
INSERT INTO answers VALUES(5,'import Mathlib.Data.Real.Basic','def answer : ℝ := -361');
INSERT INTO answers VALUES(6,'import Mathlib.Data.Real.Basic','def answer : Set (ℝ × ℝ × ℝ) := {(a, b, c) | a + b = c}');
INSERT INTO answers VALUES(7,'import Mathlib.Data.Nat.Basic','def answer : Set (ℤ × ℤ) := ∅');
INSERT INTO answers VALUES(8,'import Mathlib.Data.Complex.Basic','def answer : ℂ := -1');
INSERT INTO answers VALUES(9,'','def answer : Prop := True');
INSERT INTO answers VALUES(10,'import Mathlib.Data.Real.Basic',unistr('def answer : Set (ℝ × ℝ × ℝ) :=\u000a  {(0, 0, 0), (-1, -1, -1), (0, -2, -2), (-2, 0, -2), (-2, -2, 0)}'));
INSERT INTO answers VALUES(11,'import Mathlib.Data.Real.Basic','def answer : ℝ := 171.5');
INSERT INTO answers VALUES(12,'import Mathlib.Data.Nat.Basic','def answer : ℤ := 0');
INSERT INTO answers VALUES(13,'import Mathlib.Data.Real.Basic','def answer (n : ℕ) : ℝ := n');
INSERT INTO answers VALUES(14,'import Mathlib.Data.Nat.Basic','def answer : ℕ := 36');
INSERT INTO answers VALUES(15,'import Mathlib.Data.Nat.Basic','def answer : Set ℕ := {2, 3, 7, 23}');
INSERT INTO answers VALUES(16,'import Mathlib.Data.Nat.Basic','def answer : ℤ := 2501');
INSERT INTO answers VALUES(17,'import Mathlib.Data.Nat.Basic','def answer : ℕ := 2');
INSERT INTO answers VALUES(18,'import Mathlib.Data.Real.Basic','def answer (α : ℝ) : Set (ℝ → ℝ) := if α = -1 then {fun x ↦ x} else ∅');
INSERT INTO answers VALUES(19,'import Mathlib.Data.Nat.Basic','def answer : Set (ℕ → ℕ) := {fun _ ↦ c | c}');
INSERT INTO answers VALUES(20,'import Mathlib.Data.Nat.Basic','def answer : Set (ℤ × ℤ) := {(0, 0)}');
INSERT INTO answers VALUES(21,'import Mathlib.Data.Nat.Basic','def answer : Set (ℤ × ℤ) := {(1, 1)}');
INSERT INTO answers VALUES(22,'import Mathlib.Data.Nat.Basic','def answer : ℕ := 100');
INSERT INTO answers VALUES(23,'import Mathlib.Data.Real.Basic','def answer : Set ℝ := {0, -1, 1, -2, 2}');
CREATE TABLE problems (
  id integer primary key,
  title text not null,
  statement text not null,
  template text not null,
  answer integer,
  contest integer, archived integer default 1 not null,
  foreign key (answer) references answers(id),
  foreign key (contest) references contest(id)
);
INSERT INTO problems VALUES(1,'rfl','Prove that $1 + 1 = 2$. Hint: use `rfl`.','theorem solution : 1 + 1 = 2 := sorry',NULL,NULL,1);
INSERT INTO problems VALUES(2,'EGMO 2023 Problem 1','There are $n \ge 3$ positive real numbers $a_1, a_2, ..., a_n$. For each $1 \le i \le n$ we let $b_i = \frac{a_{i-1} + a_{i+1}}{a_i}$ (here we define $a_0$ to be $a_n$ and $a_{n+1}$ to be $a_1$). Assume that for all $i$ and $j$ in the range $1$ to $n$, we have $a_i \le a_j$ if and only if $b_i ≤ b_j$. Prove that $a_1 = a_2 = ... = a_n$.',unistr('import Mathlib.Data.Real.Basic\u000a\u000atheorem solution (n : ℕ) [NeZero n] (hn : n ≥ 3) (a : Fin n → ℝ) (ha : ∀ i, a i > 0) \u000a    (b : Fin n → ℝ) (hb : ∀ i, b i = (a (i - 1) + a (i + 1)) / (a i)) \u000a    (h : ∀ i j, a i ≤ a j ↔ b i ≤ b j) : ∀ i j, a i = a j := by\u000a  sorry\u000a'),NULL,NULL,1);
INSERT INTO problems VALUES(3,'A Number Theory Problem','Let $a$, $b$, and $n$ be positive integers with $a > b > 1$. Suppose that $b$ is odd and that $b^n$ divides $a^n - 1$. Show that $a ^ b > \frac{3 ^ n}{n}$.',unistr('import Mathlib.Algebra.Ring.Parity\u000a\u000atheorem solution {a b n : ℕ} (hs : a > b ∧ b > 1) (hn : n > 0) (ho : Odd b)\u000a    (hd : b ^ n ∣ a ^ n - 1) : n * a ^ b > 3 ^ n := sorry\u000a'),NULL,NULL,1);
INSERT INTO problems VALUES(4,'Asymmetric Inequality','Let $a, b, c$ be positive real numbers such that $\frac{1}{a} + \frac{1}{b} + \frac{1}{c} = 1$. Show that $$a + b + c \le \sqrt{b ^ 3 + a c ^ 2 + a ^ 2 c}.$$',unistr('import Mathlib.Data.Real.Sqrt\u000a\u000atheorem solution (a b c : ℝ) (ha : a > 0) (hb : b > 0) (hc : c > 0)\u000a    (h : 1 / a + 1 / b + 1 / c = 1) : a + b + c ≤ √ (b ^ 3 + a * c ^ 2 + a ^ 2 * c) := sorry\u000a'),NULL,NULL,1);
INSERT INTO problems VALUES(5,'PowGCD','Let $a, n$ be integers and $n > 0$. Prove that $n$ divides $\sum_{k=1}^{n} a^{\gcd(k, n)}$.',unistr('import Mathlib.Order.Interval.Finset.Nat\u000aimport Mathlib.Data.Fintype.BigOperators\u000a\u000atheorem solution {a : ℤ} {n : ℕ} (hn : n > 0) :\u000a    (n : ℤ) ∣ ∑ k ∈ (Finset.Icc 1 n), a ^ (k.gcd n) := sorry\u000a'),NULL,NULL,1);
INSERT INTO problems VALUES(6,'USA TSTST 2024 Problem 5',unistr('For a positive integer $k$, let $s(k)$ denote the number of $1$s in the binary representation of $k$. Prove that for any positive integer $n$,\u000d\u000a$$\\sum_{i=1}^{n}(-1)^{s(3i)} > 0.$$'),unistr('import Mathlib.Data.Nat.BitIndices\u000aimport Mathlib.Data.Fintype.BigOperators\u000aimport Mathlib.Order.Interval.Finset.Nat\u000a\u000atheorem solution (n : ℕ) (hn : n > 0) :\u000a    ∑ i ∈ (Finset.Icc 1 n), (-1) ^ (Nat.bitIndices (3 * i)).length > 0 := sorry\u000a'),NULL,NULL,1);
INSERT INTO problems VALUES(7,'PolyChoose','Let $m, n$ be natural numbers. Prove that the polynomial $$\sum_{i = 0}^{m} {n + i \choose n} x^i$$ has at most one root (including multiplicities).',unistr('import Mathlib.Data.Fintype.BigOperators\u000aimport Mathlib.Order.Interval.Finset.Nat\u000aimport Mathlib.Data.Real.Basic\u000aimport Mathlib.Algebra.Polynomial.Roots\u000a\u000anoncomputable\u000adef P (m n : ℕ) : Polynomial ℝ :=\u000a    ∑ i ∈ Finset.Icc 0 m, Polynomial.monomial i ((n + i).choose n)\u000a\u000atheorem solution (m n : ℕ) : (P m n).roots.card ≤ 1 := sorry\u000a'),NULL,NULL,1);
INSERT INTO problems VALUES(8,'Resistive Inequality','Given natural numbers $m$ and $n$, let $a$ be a positive function from $\{0, \dots, m - 1\} \times \{0, \dots n - 1\}$ to the reals. Prove that $$\sum_{i = 0}^{m - 1} \frac{1}{\sum_{j = 0}^{n - 1} \frac{1}{a(i, j)}} \le \frac{1}{\sum_{j = 0}^{n - 1} \frac{1}{\sum_{i = 0}^{m - 1} a(i, j)}}.$$',unistr('import Mathlib.Data.Finset.Basic\u000aimport Mathlib.Data.Real.Basic\u000aimport Mathlib.Data.Fintype.BigOperators\u000aopen Finset\u000a\u000atheorem solution (m n : ℕ) (a : ℕ → ℕ → ℝ) (h_pos : ∀ i < m, ∀ j < n, 0 < a i j) :\u000a    ∑ i ∈ range m, 1 / (∑ j ∈ range n, 1 / a i j) ≤\u000a    1 / (∑ j ∈ range n, 1 / (∑ i ∈ range m, a i j)) := sorry\u000a'),NULL,NULL,1);
INSERT INTO problems VALUES(9,'Permutation Tables','Prove that there exist infinitely many tables with $3$ rows and $n$ columns containing exactly numbers from $1$ to $3n$ such that the third row is the component-wise sum of the first two rows. The number of columns $n$ may vary.',unistr('import Mathlib.Data.Fintype.Basic\u000aimport Mathlib.Order.Interval.Finset.Nat\u000a\u000astructure Table (n : ℕ) where\u000a  row1 : ℕ → ℕ\u000a  row2 : ℕ → ℕ\u000a  row3 : ℕ → ℕ\u000a\u000adef Table.valid {n : ℕ} (T : Table n) : Prop :=\u000a  ∀ j ∈ Finset.Icc 1 n, T.row3 j = T.row1 j + T.row2 j\u000a\u000adef Table.range {n : ℕ} (T : Table n) : Finset ℕ :=\u000a  (Finset.Icc 1 n).image T.row1 ∪\u000a  (Finset.Icc 1 n).image T.row2 ∪\u000a  (Finset.Icc 1 n).image T.row3\u000a\u000adef Table.permutation {n : ℕ} (T : Table n) : Prop :=\u000a  T.range = Finset.Icc 1 (3 * n)\u000a\u000atheorem solution : ∀ N : ℕ, ∃ n ≥ N, ∃ T : Table n, T.valid ∧ T.permutation := sorry\u000a'),NULL,NULL,1);
INSERT INTO problems VALUES(10,'CapSet','What is the minimum number $n$ such that for any set of $n$ integer triples $T$, there are three pair-wise distinct triples $(a_1, a_2, a_3), (b_1, b_2, b_3), (c_1, c_2, c_3) \in T$ with $a_1 + b_1 + c_1$, $a_2 + b_2 + c_2$, and $a_3 + b_3 + c_3$ all divisible by $3$.',unistr('import Mathlib.Data.Finset.Card\u000aimport Mathlib.Order.Bounds.Defs\u000a\u000adef answer : ℕ := sorry\u000a\u000adef S : Set ℕ := { n | ∀ T : Finset (ℤ × ℤ × ℤ),\u000a    T.card = n → ∃ a ∈ T , ∃ b ∈ T, ∃ c ∈ T, (a ≠ b ∧ b ≠ c ∧ c ≠ a) ∧\u000a    (3 ∣ a.1 + b.1 + c.1) ∧ (3 ∣ a.2.1 + b.2.1 + c.2.1) ∧ (3 ∣ a.2.2 + b.2.2 + c.2.2) }\u000a\u000atheorem solution : IsLeast S answer := sorry\u000a'),NULL,NULL,1);
INSERT INTO problems VALUES(11,'RMM 2023 Shortlist N1','Let $n$ be a positive integer. Let $S$ be a set of ordered pairs $(x, y)$ such that $1 \le x \le n$ and $0 \le y \le n$ in each pair, and there are no pairs $(a, b)$ and $(c, d)$ of different elements in $S$ such that $a^2 + b ^ 2$ divides both $ac + bd$ and $ad - bc$. In terms of $n$, determine the size of the largest possible set $S$.',unistr('import Mathlib.Data.Finset.Card\u000aimport Mathlib.Order.Bounds.Defs\u000a\u000adef answer (n : ℕ) : ℕ := sorry\u000a\u000adef S (n : ℕ) : Set ℕ := { a : ℕ | ∃ S : Finset (ℕ × ℕ), S.card = a ∧\u000a    (∀ p ∈ S, 1 ≤ p.1 ∧ p.1 ≤ n ∧ 0 ≤ p.2 ∧ p.2 ≤ n) ∧\u000a    (∀ u ∈ S, ∀ v ∈ S, u ≠ v → ¬(\u000a      (u.1 ^ 2 + u.2 ^ 2) ∣ (u.1 * v.1 + u.2 * v.2) ∧\u000a      (u.1 ^ 2 + u.2 ^ 2) ∣ (u.1 * v.2 - u.2 * v.1))) }\u000a\u000atheorem solution (n : ℕ) (hn : n > 0) : IsGreatest (S n) (answer n) := sorry\u000a'),NULL,NULL,1);
INSERT INTO problems VALUES(12,'C','Let $k$ be an even natural number. Show that $3 ^ k + 1$ is divisible by $2$ but not by $4$.',unistr('import Mathlib.Algebra.Ring.Parity\u000a\u000atheorem solution (k : ℕ) (hk : Even k) : 2 ∣ 3 ^ k + 1 ∧ ¬ 4 ∣ 3 ^ k + 1 := sorry\u000a'),NULL,NULL,1);
INSERT INTO problems VALUES(13,'2021 OMA Intercolegial Level 2 Problem 1','The average of 16 numbers is equal to 168 . The numbers are modified as follows: 3 is subtracted from each of the first 8 numbers and 10 is added to each of the last 8 numbers. Determine the value of the average of the 16 numbers obtained.',unistr('import Mathlib.Analysis.RCLike.Basic\u000d\u000a\u000d\u000adef answer : ℝ := sorry\u000d\u000a\u000d\u000anoncomputable\u000d\u000adef List.Vector.mean (v : List.Vector ℝ 16) : ℝ :=\u000d\u000a  v.toList.sum / 16\u000d\u000a\u000d\u000adef List.Vector.modify (v : List.Vector ℝ 16) : List.Vector ℝ 16 :=\u000d\u000a  List.Vector.ofFn <| fun i ↦\u000d\u000a    if i < 8 then\u000d\u000a      v.get i - 3\u000d\u000a    else\u000d\u000a      v.get i + 10\u000d\u000a\u000d\u000atheorem solution : ∀ v : List.Vector ℝ 16, v.mean = 168 → (v.modify).mean = answer := sorry'),11,NULL,1);
INSERT INTO problems VALUES(14,'2021 OMA Intercolegial Level 2 Problem 2','Maria writes a list of numbers using the following rule: if the last two numbers written are $a$ and $b$ , then the next number is $ab − 1$. The first two numbers were $1$ and $2$. Determine what number occupies position $2021$ in her list.',unistr('import Mathlib.Algebra.Order.Group.Nat\u000d\u000a\u000d\u000anoncomputable\u000d\u000adef l : ℕ → ℤ\u000d\u000a  | 0 => 1\u000d\u000a  | 1 => 2\u000d\u000a  | n + 2 => l (n + 1) * l n - 1\u000d\u000a\u000d\u000adef answer : ℤ := sorry\u000d\u000a\u000d\u000atheorem solution : l (2021 - 1) = answer := sorry'),12,NULL,1);
INSERT INTO problems VALUES(15,'Recursive Sequence Bound','Let $a$ be sequence of real numbers such that $a_0 > 0$ and for all natural $n$, $$a_{n + 1} = a_{n} + \frac{n + 1}{a_n}.$$ Show that there exists a real number $c$ such that for all natural $n$, $$a_n \le n + 1 + \frac{c}{n + 1}.$$',unistr('import Mathlib.Data.Real.Basic\u000a\u000atheorem solution (a : ℕ → ℝ) (ha_1 : 0 < a 0) (ha_rec : ∀ n : ℕ, a (n+1) = a n + (n + 1) / a n) :\u000a    ∃ c : ℝ , ∀ n : ℕ, a n ≤ (n + 1) + c / (n + 1) := sorry\u000a'),NULL,NULL,1);
INSERT INTO problems VALUES(16,'Sequential Divison','Let $a$ be a sequence of natural numbers defined by $a_0 = a_1 = 1$, $a_2 = 2$, and $a_{n + 2} = a_n a_{n + 1} + a_n$ for all natural $n$. Show that for all natural $n \ge 5$, $a_n ^ n$ divides $a_{a_n}$.',unistr('import Mathlib.Data.Nat.Basic\u000a\u000adef a : ℕ → ℕ\u000a  | 0 => 1\u000a  | 1 => 1\u000a  | 2 => 2\u000a  | n + 2 => a n * a (n+1) + a n\u000a\u000atheorem solution (n : ℕ) (hn : n ≥ 5) : a n ^ n ∣ a (a n) := sorry\u000a'),NULL,NULL,1);
INSERT INTO problems VALUES(17,'Square Add 5 Square','Let $S$ be a set of natural numbers of the form $a ^ 2 + 5 b ^ 2$, where $a$ and $b$ are coprime positive natural numbers. Let $p \equiv 3 \pmod{4}$ be a prime dividing some element of $S$. Show that $2p$ is an element of $S$.',unistr('import Mathlib.Data.Nat.Prime.Defs\u000a\u000adef S : Set ℕ := { n | ∃ a b : ℕ, a > 0 ∧ b > 0 ∧ a.Coprime b ∧ n = a ^ 2 + 5 * b ^ 2 }\u000a\u000atheorem solution (p : ℕ) (hp : Nat.Prime p) (hpmod : p % 4 = 3) (hsp : ∃ n ∈ S, p ∣ n) :\u000a    2 * p ∈ S := sorry\u000a'),NULL,NULL,1);
INSERT INTO problems VALUES(18,'Bulgaria TST 2009 Problem ?','Let $a, b, c$ be sequences of real numbers with positive partial sums. Show that $$(\sum_{i = 1}^{n} \sum_{j = 1}^{n} \frac{a_i a_j}{c_i + c_j})(\sum_{i = 1}^{n} \sum_{j = 1}^{n} \frac{b_i b_j}{c_i + c_j}) \ge (\sum_{i = 1}^{n} \sum_{j = 1}^{n} \frac{a_i b_j}{c_i + c_j})^2.$$',unistr('import Mathlib.Data.Fintype.BigOperators\u000aimport Mathlib.Data.Real.Basic\u000aimport Mathlib.Order.Interval.Finset.Nat\u000aimport Mathlib.Data.Finset.Basic\u000a\u000atheorem solution (a b c : ℕ → ℝ) (n : ℕ) (hn : n ≥ 1) (ha : ∀ i ∈ Finset.Icc 1 n, a i > 0)\u000a    (hb : ∀ i ∈ Finset.Icc 1 n, b i > 0) (hc : ∀ i ∈ Finset.Icc 1 n, c i > 0) :\u000a    (∑ i ∈ Finset.Icc 1 n, ∑ j ∈ Finset.Icc 1 n, a i * a j / (c i + c j)) *\u000a    (∑ i ∈ Finset.Icc 1 n, ∑ j ∈ Finset.Icc 1 n, b i * b j / (c i + c j)) ≥\u000a    (∑ i ∈ Finset.Icc 1 n, ∑ j ∈ Finset.Icc 1 n, a i * b j / (c i  +c j)) ^ 2 := sorry\u000a'),NULL,NULL,1);
INSERT INTO problems VALUES(19,'2018 OMA Intercolegial Level 2 Problem 1','The following board with numbers in its squares is given:$$\begin{array}{|c|c|c|} \hline 1 & 2 & 3 \\ \hline 4 & 5 & 6 \\ \hline 7 & 8 & 9 \\ \hline \end{array}$$At each step it is possible to add $1$ to each cell in a row, add $1$ to each cell in a column, subtract $1$ from each cell in a row, or subtract $1$ from each cell in a column. Show a list of steps that transform the given board into the following board:$$\begin{array}{|c|c|c|} \hline 9 & 8 & 7 \\ \hline 6 & 5 & 4 \\ \hline 3 & 2 & 1 \\ \hline \end{array}$$',unistr('import Mathlib.LinearAlgebra.Matrix.RowCol\u000d\u000a\u000d\u000a-- 3 × 3 board of integers\u000d\u000aabbrev Board := Matrix (Fin 3) (Fin 3) ℤ\u000d\u000a\u000d\u000ainductive OpTy\u000d\u000a  | Row\u000d\u000a  | Col\u000d\u000a\u000d\u000aopen OpTy\u000d\u000a\u000d\u000ainductive OpDir\u000d\u000a  | Inc\u000d\u000a  | Dec\u000d\u000a\u000d\u000aopen OpDir\u000d\u000a\u000d\u000adef OpDir.delta : OpDir → ℤ\u000d\u000a  | Inc => 1\u000d\u000a  | Dec => -1\u000d\u000a\u000d\u000astructure Step where\u000d\u000a  opType : OpTy\u000d\u000a  ix : Fin 3\u000d\u000a  direction : OpDir\u000d\u000a\u000d\u000adef Step.delta (op : Step) : ℤ :=\u000d\u000a  op.direction.delta\u000d\u000a\u000d\u000adef Step.app (op : Step) (b : Board) : Board :=\u000d\u000a  match op.opType with\u000d\u000a  | Row =>\u000d\u000a      b + Matrix.updateRow 0 op.ix (List.Vector.replicate 3 op.delta).get\u000d\u000a  | Col =>\u000d\u000a      b + Matrix.updateCol 0 op.ix (List.Vector.replicate 3 op.delta).get\u000d\u000a\u000d\u000adef applySteps (ops : List Step) (b : Board) : Board :=\u000d\u000a  ops.foldl (fun acc op => op.app acc) b\u000d\u000a\u000d\u000a\u000d\u000adef initial : Board :=\u000d\u000a  ![![1, 2, 3],\u000d\u000a    ![4, 5, 6],\u000d\u000a    ![7, 8, 9]]\u000d\u000a\u000d\u000adef final : Board :=\u000d\u000a  ![![9, 8, 7],\u000d\u000a    ![6, 5, 4],\u000d\u000a    ![3, 2, 1]]\u000d\u000a\u000d\u000adef answer : List Step := sorry\u000d\u000a\u000d\u000atheorem solution : applySteps answer initial = final := sorry'),NULL,NULL,1);
INSERT INTO problems VALUES(20,'Latvian National 2025 Grade 12 Problem 1','Prove that for all positive integers $n$, $2^{2n-1} 3^{n-1} + 5^n$ is divisible by $7$.',unistr('import Mathlib.Data.Nat.Basic\u000a\u000atheorem solution (n : ℕ) (hn : n > 0) : 7 ∣ 2 ^ (2 * n - 1) * 3 ^ (n - 1) + 5 ^ n := sorry\u000a'),NULL,NULL,1);
INSERT INTO problems VALUES(21,'Latvian National 2025 Grade 12 Problem 3',unistr('For positive real numbers $x$, $y$, $z$ it holds that $x + y + z = 1$. Prove that\u000d\u000a$$\\frac{1}{xy - z + 2} + \\frac{1}{yz - x + 2} + \\frac{1}{xz - y + 2} \\ge \\frac{27}{16}.$$'),unistr('import Mathlib.Data.Real.Basic\u000a\u000atheorem solution (x y z : ℝ) (hx : x > 0) (hy : y > 0) (hz : z > 0) (h : x + y + z = 1) :\u000a    1 / (x * y - z + 2) + 1 / (y * z - x + 2) + 1 / (x * z - y + 2) ≥ (27 : ℝ) / 16 := sorry\u000a'),NULL,NULL,1);
INSERT INTO problems VALUES(22,'Latvian National 2025 Grade 12 Problem 4','Prime numbers $p$ and $q$ are such that $p^2 + pq + q^2$ is a square of some positive integer. Prove that $p^2 - pq + q^2$ is a prime number.',unistr('import Mathlib.Data.Nat.Prime.Defs\u000a\u000atheorem solution (p q : ℕ) (hp : p.Prime) (hq : q.Prime)\u000a    (h : ∃ a, p ^ 2 + p * q + q ^ 2 = a ^ 2) : (p ^ 2 + q ^ 2 - p * q).Prime := sorry\u000a'),NULL,NULL,1);
INSERT INTO problems VALUES(23,'Rational Cube Sum','Let $n$ be a non-negative rational number such that there are rational $x$ and $y$ with $x^3 + y ^ 3 = n$. Show that there are non-negative rational $a$ and $b$ such that $a ^ 3 + b ^ 3 = n$.',unistr('import Mathlib.Data.Rat.Init\u000a\u000atheorem solution (n : ℚ) (h1 : n ≥ 0) (h2 : ∃ x y, x ^ 3 + y ^ 3 = n) :\u000a    ∃ a b : NNRat, a ^ 3 + b ^ 3 = n := sorry\u000a'),NULL,NULL,1);
INSERT INTO problems VALUES(24,'Korean National 2010 Problem 3','There are $n$ websites $1, 2, \dots, n$ ($n \ge 2$). If there is a link from $i$ to $j$, then we can use it to move from $i$ to $j$. In this problem only links with $i < j$ are allowed. For all $i \in \{1, 2, \dots, n - 1\}$, there is a link from $i$ to $i + 1$. Prove that we can add no more than $3(n - 1)\log_2(\log_2 n)$ links so that for all $i, j$ such that $i < j$, we can move from $i$ to $j$ using at most $3$ links.',unistr('import Mathlib.Data.Finset.Basic\u000aimport Mathlib.Order.Interval.Finset.Nat\u000aimport Mathlib.Analysis.SpecialFunctions.Log.Base\u000a\u000adef is_link (n : ℕ) (e : ℕ × ℕ) : Prop := 1 ≤ e.1 ∧ e.1 < e.2 ∧ e.2 ≤ n\u000adef one_jump (L : Finset (ℕ × ℕ)) (i j : ℕ) : Prop := (i, j) ∈ L\u000adef two_jump (L : Finset (ℕ × ℕ)) (i j : ℕ) : Prop := ∃ k, (i, k) ∈ L ∧ (k, j) ∈ L\u000adef three_jump (L : Finset (ℕ × ℕ)) (i j : ℕ) : Prop :=\u000a    ∃ k₁ k₂, (i, k₁) ∈ L ∧ (k₁, k₂) ∈ L ∧ (k₂, j) ∈ L\u000a\u000atheorem solution (n : ℕ) (hn : n ≥ 2) : ∃ L : Finset (ℕ × ℕ),\u000a    (∀ e ∈ L, is_link n e) ∧\u000a    (∀ i ∈ Finset.Icc 1 (n - 1), (i, i + 1) ∈ L) ∧\u000a    (L.card ≤ n - 1 + 3 * (n - 1) * (Real.logb 2 (Real.logb 2 n))) ∧\u000a    (∀ i ∈ Finset.Icc 1 n, ∀ j ∈ Finset.Icc 1 n, i < j →\u000a      one_jump L i j ∨ two_jump L i j ∨ three_jump L i j) := sorry\u000a'),NULL,NULL,1);
INSERT INTO problems VALUES(25,'xyzzy','This is a special problem that doesn''t have a real template and can be used to submit a solution to any custom problem. It can also be used to test the checker against potential exploits (please, create an issue on [GitHub](https://github.com/Lean-Online-Judge/leanoj-checker/issues) if you find one). Submissions are not visible to other participants but still visible to the admin.','theorem solution : sorry := sorry',NULL,NULL,1);
INSERT INTO problems VALUES(26,'Coefficients Product Bound','Let $a, b, c$ be complex numbers. If for any complex number $z$ satisfying $|z| \le 1$, we have $|az^2 + bz + c| \le 1$, find the maximum possible value of $|bc|$.',unistr('import Mathlib.Analysis.Complex.Norm\u000a\u000adef S : Set ℝ :=\u000a    { t | ∃ a b c : ℂ, (∀ z : ℂ, ‖z‖ ≤ 1 → ‖a * z ^ 2 + b * z + c‖ ≤ 1) ∧ (t = ‖b * c‖) }\u000a\u000adef answer : ℝ := sorry\u000a\u000atheorem solution : IsGreatest S answer := sorry\u000a'),NULL,NULL,1);
INSERT INTO problems VALUES(27,'2025 Israel National Olympiad Problem 7',unistr('For a positive integer $n$, let $A_n$ be the set of quadruplets $(a,b,c,d)$ of integers, satisfying the following properties simultaneously:\u000d\u000a$0\\le a\\le c\\le n,$\u000d\u000a$0\\le b\\le d\\le n,$\u000d\u000a$c+d>n,$ and\u000d\u000a$bc=ad+1.$\u000d\u000aMoreover, define\u000d\u000a$$\\alpha_n=\\sum_{(a,b,c,d)\\in A_n}\\frac{1}{ab+cd}.$$\u000d\u000aFind all real numbers $t$ such that $\\alpha_n>t$ for every positive integer $n$.'),unistr('import Mathlib.Data.Real.Basic\u000aimport Mathlib.Data.Fintype.BigOperators\u000aopen Finset\u000aopen BigOperators\u000a\u000adef A (n : ℕ) : Finset ((ℕ × ℕ) × (ℕ × ℕ)) :=\u000a    ((range (n + 1) ×ˢ range (n + 1)) ×ˢ (range (n + 1) ×ˢ range (n + 1))).filter\u000a    (fun ((a, b), (c, d)) => a ≤ c ∧ b ≤ d ∧ c + d > n ∧ b * c = a * d + 1)\u000a\u000anoncomputable def α (n : ℕ) : ℝ := ∑ x ∈ A n, (1 : ℝ) / (x.1.1 * x.1.2 + x.2.1 * x.2.2)\u000a\u000anoncomputable def answer : ℝ := sorry\u000a\u000atheorem solution : IsGLB { α n | n > 0 } answer := sorry\u000a'),NULL,NULL,1);
INSERT INTO problems VALUES(28,'Fan–Taussky–Todd Inequality','Given an integer $n\ge 1$, real numbers $b_0, b_1, \dots, b_{n-1}$ satisfy the conditions $\sum_{i=0}^{n-1} b_i = 0$. Prove that $\sum_{i=0}^{n-1}{b_ib_{i+1}}\le \cos\frac{2\pi}{n}\sum_{i=0}^{n-1}{b_i^2}$, where $b_n = b_0$.',unistr('import Mathlib.Data.Real.Basic\u000aimport Mathlib.Data.Fintype.BigOperators\u000aimport Mathlib.Analysis.Complex.Trigonometric\u000aimport Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic\u000aopen Real\u000a\u000atheorem solution (n : ℕ) (hn : n > 0) (b : ℕ → ℝ) (hb : ∑ i ∈ Finset.range n, b i = 0) (hb_round : b 0 = b n) :\u000a    ∑ i ∈ Finset.range n, b i * (b (i + 1)) ≤ (cos (2 * π / n)) * ∑ i ∈ Finset.range n, (b i) ^ 2 := sorry\u000a'),NULL,NULL,1);
INSERT INTO problems VALUES(29,'Kazakhstan District 2025 Grade 11 Problem 1','Let $a, b$ be non-negative real numbers such that $a + b = 1$. Show that $$\frac{a ^ 2 + b ^ 2}{2} \le a ^ 3 + b ^ 3 \le a ^ 2 + b ^ 2.$$',unistr('import Mathlib.Data.Real.Basic\u000a\u000atheorem solution (a b : ℝ) (ha : 0 ≤ a) (hb : 0 ≤ b) (h : a + b = 1) :\u000a    (a ^ 2 + b ^ 2) / 2 ≤ a ^ 3 + b ^ 3 ∧ a ^ 3 + b ^ 3 ≤ a ^ 2 + b ^ 2 := sorry\u000a'),NULL,NULL,1);
INSERT INTO problems VALUES(30,'Latvian National 2025 Grade 10 Problem 1',unistr('Do there exist integers $a, b, c, d$ such that\u000d\u000a$$|a - b| + |b - c| + |c - d| + |d - a| = 2025?$$'),unistr('import Mathlib.Algebra.Group.Int.Defs\u000d\u000aimport Mathlib.Algebra.Order.Group.Unbundled.Abs\u000d\u000a\u000d\u000adef answer : Prop := sorry\u000d\u000a\u000d\u000atheorem solution : (∃ a b c d : ℤ, |a - b| + |b - c| + |c - d| + |d - a| = 2025) ↔ answer := sorry'),1,NULL,1);
INSERT INTO problems VALUES(31,'Kazakhstan Regional 2026 Grade 11 Problem 1','Find all functions $f : \mathbb{R} \to \mathbb{R}$ such that for any reals $x, y$, $$f(f(y) + x - y) + f(x - y) = f(xf(y) - y).$$',unistr('import Mathlib.Data.Real.Basic\u000d\u000a\u000d\u000adef P (f : ℝ → ℝ) := ∀ x y, f (f y + x - y) + f (x - y) = f (x * f y - y)\u000d\u000a\u000d\u000adef answer : Set (ℝ → ℝ) := sorry\u000d\u000a\u000d\u000atheorem solution (f : ℝ → ℝ) : P f ↔ f ∈ answer := sorry'),2,NULL,1);
INSERT INTO problems VALUES(32,'Fibonacci Divisibility','Let $p$ be an odd prime. Define $f_n$ to be the Fibonacci number (starting with $f_0 = 0$, $f_1 = 1$). Prove that $p$ divides $$\sum_{i=1}^{p-1} f_i \frac {(p-1)!} i.$$',unistr('import Mathlib.Data.Nat.Fib.Basic\u000aimport Mathlib.Data.Fintype.BigOperators\u000aimport Mathlib.Data.Nat.Factorial.Basic\u000aimport Mathlib.Order.Interval.Finset.Nat\u000aimport Mathlib.Data.Nat.Prime.Defs\u000a\u000atheorem solution (p : ℕ) (hp1 : Nat.Prime p) (hp2 : Odd p) :\u000a    p ∣ ∑ n ∈ Finset.Icc 1 (p - 1), (Nat.fib n) * (p - 1).factorial / n := sorry\u000a'),NULL,NULL,1);
INSERT INTO problems VALUES(33,'Weighted Turán''s Theorem','Let $G = (V, E)$ be a finite undirected simple graph, $x \colon V \to \mathbb{R_{\ge 0}}$ be a weight function. Prove that $$\sum_{(u, v) \in E} x(u)x(v) \leq \frac {\omega(G) - 1} {2 \omega(G)} \left( \sum_{v \in V} x(v) \right)^2,$$ where $\omega(G)$ is the maximum number of vertices in a clique of graph $G$.',unistr('import Mathlib.Combinatorics.SimpleGraph.Clique\u000aimport Mathlib.Data.NNReal.Defs\u000a\u000atheorem solution {V : Type u} [Fintype V] [DecidableEq V]\u000a    {G : SimpleGraph V} [DecidableRel G.Adj] (x : V → NNReal) : ∑ e ∈ G.edgeFinset, (e.map x).mul ≤\u000a    (G.cliqueNum - 1 : ℕ) / (2 * G.cliqueNum) * (∑ v : V, x v) ^ 2 := sorry\u000a'),NULL,NULL,1);
INSERT INTO problems VALUES(34,'City Zhautykov 2025 Grade 8 Problem 8','Solve the system of equations in reals $$\left\{ \begin{matrix} 2\sqrt{a}=b^{2025}+c^{2025},\\ 2\sqrt{b}=a^{2025}+c^{2025}, \\ 2\sqrt{c}=a^{2025}+b^{2025}. \end{matrix}\right.$$',unistr('import Mathlib.Data.Real.Sqrt\u000d\u000a\u000d\u000adef answer : Set (ℝ × ℝ × ℝ) := sorry\u000d\u000a\u000d\u000atheorem solution (a b c : ℝ) (ha : 0 ≤ a) (hb : 0 ≤ b) (hc : 0 ≤ c) :\u000d\u000a    2 * √a = b ^ 2025 + c ^ 2025 ∧\u000d\u000a    2 * √b = a ^ 2025 + c ^ 2025 ∧\u000d\u000a    2 * √c = a ^ 2025 + b ^ 2025 ↔\u000d\u000a    (a, b, c) ∈ answer := sorry'),3,NULL,1);
INSERT INTO problems VALUES(35,'City Zhautykov 2025 Grade 8 Problem 1','What is the smallest positive integer value that can be taken by $$95a^2 + 80ab + 20b^2$$ for integers $a, b$?',unistr('import Mathlib.Data.Int.Basic\u000d\u000aimport Mathlib.Order.Bounds.Defs\u000d\u000a\u000d\u000adef answer : ℤ := sorry\u000d\u000a\u000d\u000atheorem solution : IsLeast { x > 0 | ∃ a b, x = 95 * a ^ 2 + 80 * a * b + 20 * b ^ 2} answer := sorry'),4,NULL,1);
INSERT INTO problems VALUES(36,'City Zhautykov 2024 Grade 8 Problem 1','Reals $a, b$ satisfy $a + b = ab = 19$. Find the value of $$(a^2-19a)\left(b+\frac{19}{b}\right).$$',unistr('import Mathlib.Data.Real.Basic\u000d\u000a\u000d\u000adef answer : ℝ := sorry\u000d\u000a\u000d\u000atheorem solution (a b : ℝ) (h1 : a + b = 19) (h2 : a * b = 19) :\u000d\u000a    (a ^ 2 - 19 * a) * (b + 19 / b) = answer := sorry'),5,NULL,1);
INSERT INTO problems VALUES(37,'City Zhautykov 2024 Grade 8 Problem 2','Positive real numbers $a, b, c, d$ are such that all $$ab, bc, cd, da, ac, bd, abc, abd, acd, bcd, abcd$$ are integers. Is it the case that at least one of $a, b, c, d$ must be an integer?',unistr('import Mathlib.Data.Real.Basic\u000d\u000a\u000d\u000adef P (a b c d : ℝ) := 0 < a ∧ 0 < b ∧ 0 < c ∧ 0 < d ∧\u000d\u000a    (∃ n : ℤ, n = a * b) ∧ (∃ n : ℤ, n = b * c) ∧ (∃ n : ℤ, n = c * d) ∧\u000d\u000a    (∃ n : ℤ, n = d * a) ∧ (∃ n : ℤ, n = a * c) ∧ (∃ n : ℤ, n = b * d) ∧\u000d\u000a    (∃ n : ℤ, n = a * b * c) ∧ (∃ n : ℤ, n = a * b * d) ∧\u000d\u000a    (∃ n : ℤ, n = a * c * d) ∧ (∃ n : ℤ, n = b * c * d) ∧\u000d\u000a    (∃ n : ℤ, n = a * b * c * d)\u000d\u000a\u000d\u000adef answer : Prop := sorry\u000d\u000a\u000d\u000atheorem solution : (∀ a b c d, P a b c d → ∃ n : ℤ, n = a ∨ n = b ∨ n = c ∨ n = d) ↔ answer := sorry'),1,NULL,1);
INSERT INTO problems VALUES(38,'City Zhautykov 2023 Grade 8 Problem 2','Show that for all positive reals $a, b, c$, $$\frac{a}{{bc}} + \frac{b}{{ac}} + \frac{c}{{ab}} \ge \frac{2}{a} + \frac{2}{b} - \frac{2}{c}.$$ For which $a, b, c$ does this become an equality?',unistr('import Mathlib.Data.Real.Basic\u000d\u000a\u000d\u000adef answer : Set (ℝ × ℝ × ℝ) := sorry\u000d\u000a\u000d\u000atheorem solution (a b c : ℝ) (ha : 0 < a) (hb : 0 < b) (hc : 0 < c) :\u000d\u000a    a / (b * c) + b / (a * c) + c / (a * b) ≥ 2 / a + 2 / b - 2 / c ∧\u000d\u000a    (a / (b * c) + b / (a * c) + c / (a * b) = 2 / a + 2 / b - 2 / c ↔ (a, b, c) ∈ answer) := sorry'),6,NULL,1);
INSERT INTO problems VALUES(39,'City Zhautykov 2023 Grade 8 Problem 3','Find all positive integer pairs $(x, y)$ such that $x ^ 3 = y ^ 2 + 1$.',unistr('import Mathlib.Data.Nat.Basic\u000d\u000a\u000d\u000adef answer : Set (ℤ × ℤ) := sorry\u000d\u000a\u000d\u000atheorem solution (x y : ℤ) (hx : 0 < x) (hy : 0 < y) : x ^ 3 = y ^ 2 + 1 ↔ (x, y) ∈ answer := sorry'),7,NULL,1);
INSERT INTO problems VALUES(40,'City Zhautykov 2023 Grade 8 Problem 7','Complex $x$ satisfies $x ^ 2 + x + 1 = 0$. Find the value of $x^{2023}+ \frac{1}{x^{2023}}$.',unistr('import Mathlib.Data.Complex.Basic\u000d\u000a\u000d\u000adef answer : ℂ := sorry\u000d\u000a\u000d\u000atheorem solution (x : ℂ) (h : x ^ 2 + x + 1 = 0) : x ^ 2023 + 1 / x ^ 2023 = answer := sorry'),8,NULL,1);
INSERT INTO problems VALUES(41,'Test Contest 1 Problem A','Let $x, y, z$ be positive real numbers. Show that $$x^2 + xy^2 + xyz^2 \ge 4xyz - 4.$$',unistr('import Mathlib.Data.Real.Basic\u000d\u000a\u000d\u000atheorem solution (x y z : ℝ) (hx : 0 < x) (hy : 0 < y) (hz : 0 < z) :\u000d\u000a    x ^ 2 + x * y ^ 2 + x * y * z ^ 2 ≥ 4 * x * y * z - 4 := sorry'),NULL,1,1);
INSERT INTO problems VALUES(42,'Test Contest 1 Problem B','Let $k$ be a nonnegative integer. Let $A = 2 ^ k - 2$ and $B = 2 ^ kA$. Show that $A + 1$ and $B + 1$ have the same set of prime divisors.',unistr('import Mathlib.RingTheory.Int.Basic\u000d\u000a\u000d\u000atheorem solution (k : ℕ) (p a b : ℤ) (hp : Prime p) (ha : a = 2 ^ k - 2) (hb : b = 2 ^ k * a) :\u000d\u000a    p ∣ (a + 1) ↔ p ∣ (b + 1) := sorry'),NULL,1,1);
INSERT INTO problems VALUES(43,'Test Contest 1 Problem C','Find all real solutions to the system of equations: $$\left\{ \begin{array}{l} xy = z - x - y,\\ xz = y - x - z,\\ yz = x - y - z. \end{array} \right.$$',unistr('import Mathlib.Data.Real.Basic\u000d\u000a\u000d\u000adef answer : Set (ℝ × ℝ × ℝ) := sorry\u000d\u000a\u000d\u000atheorem solution (x y z : ℝ) : \u000d\u000a    x * y = z - x - y ∧\u000d\u000a    x * z = y - x - z ∧\u000d\u000a    y * z = x - y - z ↔\u000d\u000a    (x, y, z) ∈ answer := sorry'),10,1,1);
INSERT INTO problems VALUES(47,'Wedge Product Inequality','Let $n \ge 2$ be an integer. Find the smallest real $c$ such that for any real numbers $a_1,a_2,...,a_n$ and $b_1,b_2,...,b_n$ satisfying $\sum_{i=1}^n{a_i}=\sum_{i=1}^n{b_i}=1$ the following holds: $$c\sum_{1\le i<j \le n}{(a_ib_j-a_jb_i)^2}\ge \sum_{i=1}^n{(a_i-b_i)^2}.$$',unistr('import Mathlib.Data.Real.Basic\u000d\u000aimport Mathlib.Data.Fintype.BigOperators\u000d\u000aimport Mathlib.Order.Interval.Finset.Nat\u000d\u000a\u000d\u000adef answer (n : ℕ) : ℝ := sorry\u000d\u000a\u000d\u000adef S (n : ℕ) : Set ℝ := { c | ∀ a b : ℕ → ℝ,\u000d\u000a  (∑ i ∈ Finset.Icc 1 n, a i = 1) → (∑ i ∈ Finset.Icc 1 n, b i = 1) →\u000d\u000a  (c * ∑ i ∈ Finset.Ico 1 n, ∑ j ∈ Finset.Ioc i n, (a i * b j - b i * a j) ^ 2 ≥\u000d\u000a  ∑ i ∈ Finset.Icc 1 n, (a i - b i) ^ 2) }\u000d\u000a\u000d\u000atheorem solution (n : ℕ) (hn : n ≥ 2) : IsLeast (S n) (answer n) := sorry'),13,NULL,1);
INSERT INTO problems VALUES(48,'Liouville Function Problem','Let $\lambda (n)$ be the Liouville function. Prove that there exist infinitely many positive integers $n$ such that $\lambda (n) = \lambda (n+1) = \lambda (n+2)$.',unistr('import Mathlib.Data.Nat.Factorization.Basic\u000d\u000a\u000d\u000adef Ω (n : ℕ) : ℕ := (Nat.factorization n).sum (fun _ e => e)\u000d\u000a\u000d\u000adef Liouville (n : ℕ) : ℤ := (-1) ^ (Ω n)\u000d\u000a\u000d\u000atheorem solution : ∀ N, ∃ n ≥ N,\u000d\u000a    Liouville n = Liouville (n + 1) ∧ Liouville n = Liouville (n + 2) := sorry'),NULL,NULL,1);
INSERT INTO problems VALUES(49,'Italy February Round 2025 Problem 4',unistr('Let $n$ be a positive integer. Define $f(n)$ as the sum of the digits of $n$ plus the product of the digits of $n$. For example, $f(143) = 1 + 4 + 3 + 1 \\cdot 4 \\cdot 3$. How many three-digit positive integers $m$ satisfy $$f(m) = f(m-1) + 25?$$\u000d\u000a\u000d\u000a_Note: solutions by computation are strictly prohibited >:(_'),unistr('import Mathlib.Data.Nat.Digits.Defs\u000d\u000aimport Mathlib.Order.Interval.Finset.Defs\u000d\u000aimport Mathlib.Order.Interval.Finset.Nat\u000d\u000a\u000d\u000adef answer : ℕ := sorry\u000d\u000a\u000d\u000adef f (n : ℕ) : ℕ := (Nat.digits 10 n).sum + (Nat.digits 10 n).prod\u000d\u000a\u000d\u000atheorem solution : {m ∈ Finset.Icc 100 999 | f m = f (m - 1) + 25}.card = answer := sorry'),14,NULL,1);
INSERT INTO problems VALUES(50,'Quadratic Residue Exercise','Find all prime numbers $p$ such that for all positive integers $a < p$, if $a$ is a quadratic residue of $p$, then every divisor of $a$ is still a quadratic residue of $p$.',unistr('import Mathlib.Data.Nat.Prime.Defs\u000d\u000aimport Mathlib.Data.ZMod.Defs\u000d\u000a\u000d\u000adef answer : Set ℕ := sorry\u000d\u000a\u000d\u000atheorem solution : { p : ℕ | p.Prime ∧ ∀ a, 0 < a → a < p → IsSquare (a : ZMod p) →\u000d\u000a  ∀ b, b ∣ a → IsSquare (b : ZMod p) } = answer := sorry'),15,NULL,1);
INSERT INTO problems VALUES(51,'Italy February Round 2025 P5','On 100 lines of a notebook, Federico writes 100 numbers calculated as follows: on the $n$-th line, he writes the number of prime numbers less than or equal to $n$ if $n$ is even, and the number of positive integers less than or equal to $n$ that are not prime if $n$ is odd. Finally, he adds together all 100 numbers he has written. What result does he obtain?',unistr('import Mathlib.NumberTheory.PrimeCounting\u000d\u000a\u000d\u000aopen Nat.Prime\u000d\u000a\u000d\u000adef answer : ℤ := sorry\u000d\u000a\u000d\u000adef f (n : ℕ) : ℤ := if Even n then π n else n - π n\u000d\u000a\u000d\u000atheorem solution : ∑ i ∈ Finset.range 100, f i.succ = answer := sorry'),16,NULL,1);
INSERT INTO problems VALUES(52,'China South-Eastern 2024 Problem 2','Let $P$ be a convex polygon in the plane. If the endpoints of a line segment $AB$ lie on the boundary of $P$, and the region between the two lines passing through $A$ and $B$ perpendicular to $AB$ (including the boundary) contains $P$, then the segment $AB$ is called a $J$-chord. Find the largest positive integer $k$ such that any convex polygon $P$ in the plane has $k$ $J$-chords.',unistr('import Mathlib.Analysis.InnerProductSpace.PiL2\u000d\u000a\u000d\u000aabbrev Plane := EuclideanSpace ℝ (Fin 2)\u000d\u000a\u000d\u000adef IsConvexPolygon (P : Set Plane) : Prop :=\u000d\u000a  ∃ s : Finset Plane, P = convexHull ℝ s ∧ (interior P).Nonempty\u000d\u000a\u000d\u000adef IsJChord (P : Set Plane) (A B : Plane) : Prop := A ∈ frontier P ∧ B ∈ frontier P ∧ A ≠ B ∧\u000d\u000a  ∀ X ∈ P, 0 ≤ inner ℝ (X - A) (B - A) ∧ 0 ≤ inner ℝ (X - B) (A - B)\u000d\u000a\u000d\u000adef HasAtLeastKJChords (P : Set Plane) (k : ℕ) : Prop := ∃ s : Finset (Plane × Plane),\u000d\u000a  s.card = k ∧ (∀ p ∈ s, IsJChord P p.1 p.2) ∧ (∀ p ∈ s, (p.2, p.1) ∉ s)\u000d\u000a\u000d\u000adef answer : ℕ := sorry\u000d\u000a\u000d\u000atheorem solution : IsGreatest {k : ℕ | k > 0 ∧ (∀ P : Set Plane,\u000d\u000a    IsConvexPolygon P → HasAtLeastKJChords P k)} answer := sorry'),17,NULL,1);
INSERT INTO problems VALUES(53,'Austria 2023 Final Round Problem 1','Let $\alpha$ be a nonzero real number. Determine all functions $f : \mathbb{R} → \mathbb{R}$ with $$f(f(x + y)) = f(x + y) + f(x)f(y) + \alpha xy$$ for all $x, y \in \mathbb{R}$.',unistr('import Mathlib.Data.Real.Basic\u000d\u000a\u000d\u000adef P (f : ℝ → ℝ) (α : ℝ) := ∀ x y, f (f (x + y)) = f (x + y) + f x * f y + α * x * y\u000d\u000a\u000d\u000adef answer (α : ℝ) : Set (ℝ → ℝ) := sorry\u000d\u000a\u000d\u000atheorem solution (f : ℝ → ℝ) {α : ℝ} (hα : α ≠ 0) : P f α ↔ f ∈ answer α := sorry'),18,NULL,1);
INSERT INTO problems VALUES(54,'A. City Zhautykov 2017 Problem 2','Real numbers $a, b, x, y$ are such that $(ab)^3 + (xy)^3 \ge (ax)^3 + (by)^3$. Show that $ab + xy \ge ax + by$.',unistr('import Mathlib.Data.Real.Basic\u000d\u000a\u000d\u000atheorem solution (a b x y : ℝ) (h : (a * b) ^ 3 + (x * y) ^ 3 ≥ (a * x) ^ 3 + (b * y) ^ 3) : \u000d\u000a    a * b + x * y ≥ a * x + b * y := sorry'),NULL,2,1);
INSERT INTO problems VALUES(55,'B. Kazakhstan 2020 Problem 1','Find all positive integer pairs $(m, n)$ such that $n^4$ divides $2m^5 - 1$ and $m^4$ divides $2n^5 + 1$.',unistr('import Mathlib.Algebra.Group.Int.Defs\u000d\u000aimport Mathlib.Data.Set.Defs\u000d\u000a\u000d\u000adef answer : Set (ℤ × ℤ) := sorry\u000d\u000a\u000d\u000atheorem solution (m n : ℤ) (hm : 0 < m) (hn : 0 < n) : \u000d\u000a    n ^ 4 ∣ 2 * m ^ 5 - 1 ∧ m ^ 4 ∣ 2 * n ^ 5 + 1 ↔ (m, n) ∈ answer := sorry'),21,2,1);
INSERT INTO problems VALUES(56,'C. Latvia 2021 Problem 2','Let $x, y, z$ be positive real numbers. Show that $$\frac{x ^ 2 + y ^ 2}{x + y} + \frac{y ^ 2 + z ^ 2}{y + z} + \frac{z ^ 2 + x ^ 2}{z + x} \ge x + y + z.$$',unistr('import Mathlib.Data.Real.Basic\u000d\u000a\u000d\u000atheorem solution (x y z : ℝ) (hx : 0 < x) (hy : 0 < y) (hz : 0 < z) :\u000d\u000a    (x ^ 2 + y ^ 2) / (x + y) + (y ^ 2 + z ^ 2) / (y + z) + (z ^ 2 + x ^ 2) / (z + x)\u000d\u000a    ≥ x + y + z := sorry'),NULL,2,1);
INSERT INTO problems VALUES(57,'D. Latvia 2021 Problem 5','Find all integer pairs $(a, b)$ such that $$(19 a + b) ^ {18} + (a + b) ^ {18} + (a + 19 b) ^ {18}$$ is a perfect square.',unistr('import Mathlib.Algebra.Group.Int.Defs\u000d\u000aimport Mathlib.Data.Set.Defs\u000d\u000a\u000d\u000adef answer : Set (ℤ × ℤ) := sorry\u000d\u000a\u000d\u000atheorem solution (a b : ℤ) : (∃ c, c ^ 2 = (19 * a + b) ^ 18 + (a + b) ^ 18 + (a + 19 * b) ^ 18) ↔\u000d\u000a    (a, b) ∈ answer := sorry'),20,2,1);
INSERT INTO problems VALUES(58,'E. Canada 2002 Problem 5','Determine all functions $f: \mathbb{N} \to \mathbb{N}$ such that $$xf(y) + yf(x) = (x + y)f(x^2 + y^2)$$ for all $x, y \in \mathbb{N}$.',unistr('import Mathlib.Algebra.Group.Nat.Defs\u000d\u000aimport Mathlib.Data.Set.Defs\u000d\u000a\u000d\u000adef answer : Set (ℕ → ℕ) := sorry\u000d\u000a\u000d\u000atheorem solution (f : ℕ → ℕ) : (∀ x y, x * f y + y * f x = (x + y) * f (x ^ 2 + y ^ 2)) ↔\u000d\u000a    f ∈ answer := sorry'),19,2,1);
INSERT INTO problems VALUES(59,'F. Austria 2016 Problem 6',unistr('Let $a, b, c$ be integers such that $$\\frac{ab}{c} + \\frac{ac}{b} + \\frac{bc}{a}$$ is an integer. Prove that each of the numbers $$\\frac{ab}{c}, \\frac{ac}{b}, \\frac{bc}{a}$$ is an integer.\u000d\u000a\u000d\u000a<small>Note: the template was updated after the contest.</small>'),unistr('import Mathlib.Data.Nat.Basic\u000d\u000aimport Mathlib.Data.Rat.Init\u000d\u000a\u000d\u000atheorem solution (a b c : ℤ) (ha : a ≠ 0) (hb : b ≠ 0) (hc : c ≠ 0)\u000d\u000a    (h : ∃ n : ℤ, n = (a * b) / (c : ℚ) + (a * c) / b + (b * c) / a) :\u000d\u000a    (∃ m : ℤ, m = (a * b) / (c : ℚ)) ∧\u000d\u000a    (∃ k : ℤ, k = (a * c) / (b : ℚ)) ∧\u000d\u000a    (∃ l : ℤ, l = (b * c) / (a : ℚ)) := sorry'),NULL,2,1);
INSERT INTO problems VALUES(60,'G. Austria 2015 Problem 4',unistr('Show that every positive integer ending in $133$ in decimal representation has a prime factor larger than $7$.\u000d\u000a\u000d\u000a<small>Note: the template was updated after the contest.</small>'),unistr('import Mathlib.Data.Nat.Prime.Defs\u000d\u000a\u000d\u000atheorem solution (n : ℕ) (hn : 0 < n) (h133 : n % 1000 = 133) : ∃ p > 7, p.Prime ∧ p ∣ n := sorry'),NULL,2,1);
INSERT INTO problems VALUES(61,'H. Asia Pacific 2010 Problem 2','For a positive integer $k$, call an integer a _pure $k$-th power_ if it can be represented as $m^k$ for some integer $m$. Show that for every positive integer $n$, there exist $n$ distinct positive integers such that their sum is a pure $2009$-th power, and their product is a pure $2010$-th power.',unistr('import Mathlib.Algebra.BigOperators.Group.Finset.Defs\u000d\u000aimport Mathlib.Data.Fintype.Basic\u000d\u000a\u000d\u000atheorem solution (n : ℕ) (hn : 0 < n) : ∃ a : Fin n → ℕ, (∀ i, 0 < a i) ∧\u000d\u000a    a.Injective ∧ (∃ b, ∑ i, a i = b ^ 2009) ∧ (∃ c, ∏ i, a i = c ^ 2010) := sorry'),NULL,2,1);
INSERT INTO problems VALUES(62,'I. IMO 2000 Problem 5',unistr('Does there exist a positive integer $n$ such that $n$ has exactly $2000$ distinct prime divisors and $n$ divides $2 ^ n + 1$?\u000d\u000a\u000d\u000a_Note: This problem does not yet have a formalized solution on [Compfiles](https://dwrensha.github.io/compfiles/). If you solve it, consider contributing your solution there._'),unistr('import Mathlib.Data.Nat.PrimeFin\u000d\u000a\u000d\u000adef answer : Prop := sorry\u000d\u000a\u000d\u000atheorem solution : (∃ n, 0 < n ∧ n.primeFactors.card = 2000 ∧ n ∣ 2 ^ n + 1) ↔ answer := sorry'),9,2,1);
INSERT INTO problems VALUES(63,'Cauchy-like Inequality',unistr('Prove that for any real numbers $a_1,a_2,\\cdots,a_n$ and $b_1,b_2,\\cdots,b_n$ satisfying $\\sum_{i=1}^n{a_i^2}=\\sum_{i=1}^n{b_i^2}=1$ and $\\sum_{i=1}^n{a_ib_i}=0$, the following holds:\u000d\u000a$$(\\sum_{i=1}^n{a_i})^2+(\\sum_{i=1}^n{b_i})^2\\le n$$.'),unistr('import Mathlib.Data.Real.Basic\u000d\u000aimport Mathlib.Algebra.BigOperators.Ring.Finset\u000d\u000aimport Mathlib.Order.Interval.Finset.Nat\u000d\u000a\u000d\u000atheorem solution (n : ℕ) (a b : ℕ → ℝ) (ha : ∑ i ∈ Finset.Icc 1 n, (a i) ^ 2 = 1)\u000d\u000a    (hb : ∑ i ∈ Finset.Icc 1 n, (b i) ^ 2 = 1) (hab : ∑ i ∈ Finset.Icc 1 n, (a i) * (b i) = 0) :\u000d\u000a    (∑ i ∈ Finset.Icc 1 n, a i) ^ 2 + (∑ i ∈ Finset.Icc 1 n, b i) ^ 2 ≤ n := sorry'),NULL,NULL,1);
INSERT INTO problems VALUES(64,'Partial Sum of Squares Inequality','Let $a$ be a sequence of real numbers such that $a_1+a_2+\cdots+a_n\ge\sqrt{n}$ for any $n$. Prove that $$a_1^2+a_2^2+\cdots+a_n^2>\frac{1}{4}(1+\frac{1}{2}+\cdots+\frac{1}{n})$$ for any $n$.',unistr('import Mathlib.Data.Real.Sqrt\u000d\u000a\u000d\u000atheorem solution (a : ℕ → ℝ) (ha : ∀ n ≥ 1, (∑ i ∈ Finset.Icc 1 n, a i) ≥ √n) :\u000d\u000a    ∀ n ≥ 1, (∑ i ∈ Finset.Icc 1 n, (a i) ^ 2) >\u000d\u000a      (1 : ℝ) / 4 * (∑ i ∈ Finset.Icc 1 n, (1 : ℝ) / i) := sorry'),NULL,NULL,1);
INSERT INTO problems VALUES(65,'All-Russian Regional Preparation NT Exercise 1','Natural numbers $a, b, c$ are such that $abc = 60000000$. What is the largest possible value of $\gcd(a, b, c)$?',unistr('import Mathlib.Algebra.GCDMonoid.Multiset\u000d\u000aimport Mathlib.Algebra.GCDMonoid.Nat\u000d\u000aimport Mathlib.Order.Bounds.Defs\u000d\u000a\u000d\u000adef answer : ℕ := sorry\u000d\u000a\u000d\u000atheorem solution : IsGreatest\u000d\u000a    {g | ∃ a b c : ℕ, a * b * c = 60000000 ∧ Multiset.gcd {a, b, c} = g} answer := sorry'),22,NULL,1);
INSERT INTO problems VALUES(66,'All-Russian Regional Preparation NT Exercise 2','Is it possible to arrange $2019$ positive integers in a circle so that for every two neighboring integers, one of them is equal to the other multiplied by some prime?',unistr('import Mathlib.Data.Nat.Prime.Defs\u000d\u000a\u000d\u000adef answer : Prop := sorry\u000d\u000a\u000d\u000atheorem solution : (∃ a : Fin 2019 → ℕ,\u000d\u000a    ∀ i, a i > 0 ∧ ∃ p, p.Prime ∧ (a i = p * a (i + 1) ∨ a (i + 1) = p * a i)) ↔ answer := sorry'),1,NULL,1);
INSERT INTO problems VALUES(67,'All-Russian Regional Preparation NT Exercise 3','Let there be $4$ positive integers such that each is divisible by the **gcd** and divides the **lcm** of the other three. Show that their product is a perfect square.',unistr('import Mathlib.Algebra.BigOperators.Group.Multiset.Defs\u000d\u000aimport Mathlib.Algebra.GCDMonoid.Multiset\u000d\u000aimport Mathlib.Algebra.GCDMonoid.Nat\u000d\u000a\u000d\u000atheorem solution (s : Multiset ℕ) (h1 : s.card = 4) (h2 : ∀ x ∈ s, 0 < x)\u000d\u000a    (h3 : ∀ x ∈ s, (s.erase x).gcd ∣ x) (h4 : ∀ x ∈ s, x ∣ (s.erase x).lcm) :\u000d\u000a    ∃ m, s.prod = m ^ 2 := sorry'),NULL,NULL,1);
INSERT INTO problems VALUES(68,'All-Russian Regional Preparation NT Exercise 4','Does there exist a geometric progression of $5$ two-digit natural numbers?',unistr('import Mathlib.Data.Real.Basic\u000d\u000a\u000d\u000adef answer : Prop := sorry\u000d\u000a\u000d\u000atheorem solution : (∃ a₁ a₂ a₃ a₄ a₅ : ℕ,\u000d\u000a    10 ≤ a₁ ∧ a₁ < a₂ ∧ a₂ < a₃ ∧ a₃ < a₄ ∧ a₄ < a₅ ∧ a₅ < 100 ∧\u000d\u000a    ∃ d : ℝ, d * a₁ = a₂ ∧ d * a₂ = a₃ ∧ d * a₃ = a₄ ∧ d * a₄ = a₅) ↔ answer := sorry'),9,NULL,1);
INSERT INTO problems VALUES(69,'All-Russian Regional Preparation NT Exercise 5','Does there exist an arithmetic progression of $3$ distinct positive integers such that the first is a perfect square, the second is a perfect cube, and the third is a perfect $5$-th power?',unistr('import Mathlib.Algebra.Group.Nat.Defs\u000d\u000a\u000d\u000adef answer : Prop := sorry\u000d\u000a\u000d\u000atheorem solution : (∃ a b c : ℕ, 0 < a ^ 2 ∧ a ^ 2 < b ^ 3 ∧ b ^ 3 < c ^ 5 ∧\u000d\u000a    ∃ d, a ^ 2 + d = b ^ 3 ∧ b ^ 3 + d = c ^ 5) ↔ answer := sorry'),9,NULL,1);
INSERT INTO problems VALUES(70,'Switzerland 2003','Given that $x, y \in \mathbb{R}$ satisfy $x + y = x^3 + y^3 = x^5 + y^5$, what are the possible values of $x + y$?',unistr('import Mathlib.Data.Real.Basic\u000d\u000a\u000d\u000adef answer : Set ℝ := sorry\u000d\u000a\u000d\u000atheorem solution (s : ℝ) :\u000d\u000a    (∃ x y, x + y = s ∧ x ^ 3 + y ^ 3 = s ∧ x ^ 5 + y ^ 5 = s) ↔ s ∈ answer := sorry'),23,NULL,1);
CREATE TABLE contests (
  id integer primary key,
  title text not null,
  start text not null,
  end text not null
);
INSERT INTO contests VALUES(1,'Test Contest 1','2026-02-18T18:00','2026-02-19T18:00');
INSERT INTO contests VALUES(2,'Week Long Practice Contest 1','2026-03-01T00:00','2026-03-07T23:59');
CREATE TABLE website (
  id integer primary key,
  name TEXT,
  text TEXT
);
INSERT INTO website VALUES(1,'message','');
COMMIT;
